# LED Status Configuration for URC 2026 Competition

# Hardware Configuration
hardware:
  mode: "simulation"  # "simulation" or "real"
  gpio_pins:
    red: 18
    green: 19
    blue: 20
    yellow: 21
    white: 22
  pwm_frequency: 1000  # Hz
  brightness_max: 100  # 0-100%
  brightness_min: 10   # 0-100%

# LED Patterns Configuration
patterns:
  solid_duration: 0.0      # 0 = continuous
  blink_frequency: 1.0     # Hz
  fast_blink_frequency: 5.0 # Hz
  pulse_frequency: 2.0     # Hz
  fade_duration: 2.0       # seconds
  success_flash_duration: 10.0  # seconds

# State Management Integration
state_integration:
  enabled: true
  led_info_topic: "/state_machine/led_info"
  system_state_topic: "/state_machine/system_state"
  mission_status_topic: "/mission_status"  # legacy support
  qos_reliability: "reliable"
  qos_durability: "volatile"

# Competition Requirements
competition:
  visibility_distance: 50.0  # meters
  judge_visibility_angle: 120.0  # degrees
  brightness_daylight: 100  # 0-100%
  brightness_night: 50      # 0-100%
  emergency_override: true

# LED Color Mapping
color_mapping:
  autonomous: "red"
  teleoperation: "blue"
  safety: "red"
  boot: "yellow"
  calibration: "yellow"
  idle: "green"
  shutdown: "red"
  success: "green"
  error: "red"
  transition: "white"

# Pattern Mapping
pattern_mapping:
  autonomous: "solid"
  teleoperation: "solid"
  safety: "fast_blink"
  boot: "blink"
  calibration: "solid"
  idle: "solid"
  shutdown: "fade"
  success: "blink"
  error: "fast_blink"
  transition: "pulse"

# Logging Configuration
logging:
  level: "info"  # debug, info, warn, error
  log_led_changes: true
  log_pattern_changes: true
  log_hardware_errors: true

# Performance Configuration
performance:
  update_rate: 10.0  # Hz
  timeout_duration: 5.0  # seconds
  retry_attempts: 3
  hardware_check_interval: 1.0  # seconds
