# Path-based labels for areas
"area:calibration":
  - "Autonomy/calibration/**"
"area:cv":
  - "Autonomy/computer_vision/**"
"area:navigation":
  - "Autonomy/navigation/**"
"area:slam":
  - "Autonomy/slam/**"
"area:state":
  - "Autonomy/state_management/**"
"area:deployment":
  - "Autonomy/deployment/**"
  - "development/docker/**"
  - "deployment/**"
  - "mcp-servers/**"
"visual-artifact":
  - "Autonomy/calibration/aruco_tags/**"
  - "Autonomy/calibration/print/**"
  - "RobotDefinition/**"
  - "docs/**"

