## Label taxonomy for Robotics 2025
## Apply with: "Sync Labels" workflow or run it manually from Actions

labels:
  # Areas
  - name: "area:calibration"
    color: "1f7a8c"
    description: "Calibration and camera/hand-eye work"
  - name: "area:cv"
    color: "0e7490"
    description: "Computer vision and perception"
  - name: "area:navigation"
    color: "2563eb"
    description: "Navigation, planning and control"
  - name: "area:slam"
    color: "7c3aed"
    description: "SLAM and localization"
  - name: "area:state"
    color: "059669"
    description: "State management and coordination"
  - name: "area:deployment"
    color: "6b7280"
    description: "Deployment, CI/CD, infrastructure, Raspberry Pi"

  # Types
  - name: "type:bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "type:task"
    color: "0366d6"
    description: "General task"
  - name: "type:doc"
    color: "0e8a16"
    description: "Documentation work"
  - name: "type:epic"
    color: "b60205"
    description: "Large body of work broken down into tasks"

  # Visual artifacts
  - name: "visual-artifact"
    color: "a2eeef"
    description: "Diagrams, renders, figures, and visual deliverables"

  # Priority
  - name: "priority:p0"
    color: "b60205"
    description: "Immediate, highest priority"
  - name: "priority:p1"
    color: "d876e3"
    description: "High priority"
  - name: "priority:p2"
    color: "c5def5"
    description: "Medium priority"

  # Risk
  - name: "risk:high"
    color: "b60205"
    description: "High delivery or technical risk"
  - name: "risk:med"
    color: "fbca04"
    description: "Medium risk"
  - name: "risk:low"
    color: "0e8a16"
    description: "Low risk"

  # Status helper labels (to aid project automations)
  - name: "status:todo"
    color: "ededed"
    description: "Ready to start"
  - name: "status:in-progress"
    color: "0075ca"
    description: "Work in progress"
  - name: "status:in-review"
    color: "5319e7"
    description: "In code review"
  - name: "status:blocked"
    color: "cfd3d7"
    description: "Blocked, needs attention"
  - name: "status:done"
    color: "0e8a16"
    description: "Completed"

