# Sensor Configuration Parameters for Gazebo Simulation
# Adjustable noise levels for testing sensor data quality

# Noise level presets
noise_levels:
  low:
    imu:
      gyro_bias: 0.01  # degrees/s
      gyro_noise: 0.005  # degrees/s
      accel_bias: 1.0  # mg
      accel_noise: 0.5  # mg
    gps:
      position_noise: 1.0  # meters
      velocity_noise: 0.1  # m/s
      update_rate: 10.0  # Hz
    lidar:
      range_noise: 0.01  # meters
      angular_noise: 0.001  # radians
      update_rate: 10.0  # Hz
    camera:
      depth_noise: 0.005  # meters
      rgb_noise: 0.01  # pixel variance
      update_rate: 30.0  # Hz
      
  medium:
    imu:
      gyro_bias: 0.05  # degrees/s
      gyro_noise: 0.02  # degrees/s
      accel_bias: 5.0  # mg
      accel_noise: 2.0  # mg
    gps:
      position_noise: 2.0  # meters
      velocity_noise: 0.2  # m/s
      update_rate: 5.0  # Hz
    lidar:
      range_noise: 0.03  # meters
      angular_noise: 0.005  # radians
      update_rate: 10.0  # Hz
    camera:
      depth_noise: 0.02  # meters
      rgb_noise: 0.05  # pixel variance
      update_rate: 30.0  # Hz
      
  high:
    imu:
      gyro_bias: 0.1  # degrees/s
      gyro_noise: 0.05  # degrees/s
      accel_bias: 10.0  # mg
      accel_noise: 5.0  # mg
    gps:
      position_noise: 5.0  # meters
      velocity_noise: 0.5  # m/s
      update_rate: 2.0  # Hz
    lidar:
      range_noise: 0.05  # meters
      angular_noise: 0.01  # radians
      update_rate: 5.0  # Hz
    camera:
      depth_noise: 0.05  # meters
      rgb_noise: 0.1  # pixel variance
      update_rate: 15.0  # Hz

# Real-world sensor specifications for comparison
real_world_specs:
  imu:
    gyro_bias_stability: 0.02  # degrees/s
    gyro_noise_density: 0.01  # degrees/s/√Hz
    accel_bias_stability: 2.0  # mg
    accel_noise_density: 1.0  # mg/√Hz
  gps:
    position_accuracy: 2.5  # meters (95% confidence)
    velocity_accuracy: 0.1  # m/s
    update_rate: 1.0  # Hz
  lidar:
    range_accuracy: 0.03  # meters
    angular_resolution: 0.25  # degrees
    update_rate: 10.0  # Hz
  camera:
    depth_accuracy: 0.02  # meters at 1m
    rgb_resolution: 640  # pixels
    update_rate: 30.0  # Hz

# Mission-specific sensor requirements
mission_requirements:
  autonomous_navigation:
    min_features_per_frame: 100
    max_pose_drift_per_meter: 0.01  # 1cm per meter
    max_loop_closure_error: 0.1  # 10cm
    min_slam_confidence: 0.7
  obstacle_avoidance:
    min_detection_range: 3.0  # meters
    max_obstacle_detection_time: 0.1  # seconds
    min_clearance_distance: 0.5  # meters
  gps_denied_operation:
    min_visual_features: 200
    max_drift_per_minute: 0.02  # 2cm per minute
    min_depth_accuracy: 0.05  # 5cm

# Performance thresholds
performance_thresholds:
  cpu_usage_max: 70.0  # percent
  memory_usage_max: 500.0  # MB
  memory_growth_max: 50.0  # MB per 10 minutes
  pose_update_rate_min: 5.0  # Hz
  map_update_latency_max: 0.1  # seconds

# Validation criteria
validation_criteria:
  sensor_fidelity_min: 0.8  # 80% similarity to real sensors
  slam_accuracy_max: 1.0  # 1 meter error over 500m
  navigation_success_min: 0.9  # 90% waypoint success rate
  obstacle_avoidance_success_min: 0.9  # 90% collision avoidance
  endurance_stability_min: 0.95  # 95% uptime over 30 minutes
