name: Bug
description: Report a bug
title: "[Bug] <short title>"
labels: ["type:bug", "status:todo"]
body:
  - type: input
    id: env
    attributes:
      label: Environment
      description: ROS2 version, OS, hardware
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Be specific
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
    validations:
      required: false

