name: Epic
description: Track a large body of work
title: "[Epic] <short title>"
labels: ["type:epic", "status:todo"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: Outcome and value
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: In-scope and out-of-scope
    validations:
      required: true
  - type: textarea
    id: breakdown
    attributes:
      label: Task Breakdown
      description: Link or list child issues
    validations:
      required: false
  - type: textarea
    id: risks
    attributes:
      label: Risks / Dependencies
    validations:
      required: false

