name: Task
description: Create a task for the Robotics 2025 project
title: "[Task] <short title>"
labels: ["type:task", "status:todo"]
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What needs to be done and why?
      placeholder: Clear, outcome-focused description
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Define the conditions for success
      placeholder: |
        - [ ] Condition 1
        - [ ] Condition 2
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Select the subsystem area
      options:
        - area:calibration
        - area:cv
        - area:navigation
        - area:slam
        - area:state
        - area:deployment
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - priority:p0
        - priority:p1
        - priority:p2
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Context / Links
      description: Related issues, PRs, docs
    validations:
      required: false

