name: Visual Artifact
description: Track diagrams, renders, figures, and visual deliverables
title: "[Visual] <short title>"
labels: ["visual-artifact", "type:doc", "status:todo"]
body:
  - type: input
    id: purpose
    attributes:
      label: Purpose
      description: Why this artifact is needed
    validations:
      required: true
  - type: textarea
    id: preview
    attributes:
      label: Link(s) or image reference
      description: URLs to diagrams, renders, or attach images
    validations:
      required: true
  - type: textarea
    id: sources
    attributes:
      label: Source files
      description: Paths to source (e.g., docs/, Autonomy/print/, etc.)
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
    validations:
      required: true

