# RTAB-Map Configuration for Desert RGB-D SLAM
# Tuned for low-feature environments (sand, dunes, flat terrain)

# RGB-D Specific Parameters
Rgbd/AngularUpdate: 0.15        # meters - rotation threshold for keyframe
Rgbd/LinearUpdate: 0.2          # radians - translation threshold for keyframe
Rgbd/OptimizeFromGraphEnd: true # optimize graph from the end

# Feature Detection (Critical for Low-Feature Desert)
Kp/DetectorStrategy: 5          # 5 = ORB, good for desert
Kp/MaxFeatures: 400             # Increased from default (300) for sparse desert
Kp/RoiRatios: "0.03 0.03 0.04 0.04"  # Ignore sand-colored edges

# Loop Closure (Critical in Low-Feature Environments)
Mem/RehearsalSimilarity: 0.45   # More aggressive (lower threshold)
Reg/Histogram: 0.25             # More permissive histogram matching
Loop/MinVisualInliers: 15       # Reduced from 20, more flexible
Loop/RawMonoCA: true            # Use raw monocular constraint

# Memory Management (Raspberry Pi 5 has limited RAM)
Mem/MaxMemoryMB: 500            # Max 500MB, prune aggressively
Mem/ImagePostRawca: false       # Don't post-process images
Mem/BinDataKept: false          # Aggressively prune old data
Mem/ImageKept: false            # Don't keep images in memory (save space)
Mem/BadSignaturesIgnored: true  # Skip low-quality frames

# Depth Image Parameters
Stereo/MaxDisparity: 128        # Max disparity for depth
Stereo/MinDisparity: 2          # Min disparity
Rtabmap/VeryLowMemoryMode: false # Set to true if memory becomes critical

# Localization and Map Updates
Rtabmap/CreateIntermediateNodes: false  # Don't create intermediate nodes
Rtabmap/TimeThr: 0              # No time threshold
Rtabmap/LoopThr: 0.11           # Loop closure threshold (lower = more aggressive)

# Pose Graph Optimization
RGBD/NeighborLinkRefining: true  # Refine neighbor links
RGBD/OptimizeMaxError: 0.02     # Pose graph optimization max error

# Bayesian Filtering Parameters for Low Texture
Bayes/VirtualPlacesPriorTreshold: 0.9  # Virtual places probability threshold
Bayes/PredictionLC: 0.1                # Prediction of loop closure

# Vocabulary Parameters
Kp/Dictionary: ~/.ros/rtabmap_dictionary.bin  # Use pre-trained vocabulary

# Grid Parameters
GridGlobal/Eroded: true         # Erode occupancy grid
GridGlobal/OccupancyThr: 0.5    # Occupancy threshold
Rtabmap/GraphOptimization: g2o  # Use g2o for optimization

# Recovery Parameters
Rtabmap/DetectionRate: 1.0      # How often to detect loop closures
Mem/RecentWmSize: 200           # Size of recent working memory

# Compression
Mem/CompressionParallelized: true  # Use parallel compression if available
Rtabmap/PublishStats: true      # Publish statistics for monitoring

# Constraint Parameters for GPS Integration
LoopClosure/Variance: 0.5       # Variance of loop closures (affects GPS weight)

