name: Add to User Project

on:
  issues:
    types: [opened, reopened, labeled]
  pull_request_target:
    types: [opened, reopened, ready_for_review]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Validate project URL
        run: |
          if [ -z "https://github.com/users/ahmad-kad/projects/5" ]; then
            echo "❌ Error: Project URL not set"
            exit 1
          fi
          echo "✅ Project URL configured: https://github.com/users/ahmad-kad/projects/5"
      - name: Add new items to project
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/users/ahmad-kad/projects/5
          github-token: ${{ secrets.githubToken }}
        continue-on-error: true
      - name: Log project add result
        run: |
          echo "✅ Item add attempt completed for:"
          echo "   - Issue: ${{ github.event.issue.title || 'N/A' }}"
          echo "   - PR: ${{ github.event.pull_request.title || 'N/A' }}"
      - name: Workflow error handler
        if: failure()
        run: |
          echo "⚠️ Add-to-project workflow failed. Check:"
          echo "- githubToken secret exists (Settings → Secrets)"
          echo "- Token has 'project' and 'repo' scopes"
          echo "- Project URL is correct: https://github.com/users/ahmad-kad/projects/5"
          echo "- Issue/PR is not archived"

