name: Populate Project from TODO Files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'  # Weekly on Monday at 9 AM UTC

permissions:
  contents: read
  issues: write

jobs:
  populate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Scan TODO files
        run: |
          echo "📋 Scanning *_TODO.md files..."
          find Autonomy -name "*_TODO.md" -type f | wc -l
      
      - name: Extract TODOs and create issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/extract-todos-to-issues.py
      
      - name: Log population complete
        run: |
          echo "✅ TODO extraction complete"
          echo "📊 Project board: https://github.com/users/ahmad-kad/projects/5"
      
      - name: Error handler
        if: failure()
        run: |
          echo "⚠️ TODO population workflow failed. Check:"
          echo "- GITHUB_TOKEN has 'issues:write' permission"
          echo "- Autonomy/*_TODO.md files exist"
          echo "- Python script runs without errors"
