name: Sync Labels

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - .github/labels.yml

permissions:
  contents: read
  issues: write

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply labels from .github/labels.yml
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          dry-run: false

