name: TODO to Issue

on:
  push:
    branches: [ main ]
    paths:
      - 'Autonomy/**'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create/update issues from TODOs
        uses: alstr/todo-to-issue-action@v4
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTO_ASSIGN: true
          CLOSE_ISSUES: true
          LABEL: "type:task"

