name: Validate Documentation Links

on:
  pull_request:
    paths:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          folder-path: 'Autonomy/docs,docs/'
          file-path: 'README.md,CONTRIBUTING.md'
          max-depth: 3
      - name: Log validation result
        if: success()
        run: echo "✅ All documentation links are valid"
      - name: Error handler
        if: failure()
        run: |
          echo "⚠️ Broken links found in documentation."
          echo "Check the above output for broken links and update them."
